glm-tools/pyglmnet

pyglmnet.py
pyglmnet_example.ipynb

I will remove scikit learn dependency later

Multinomial regression added with scikit-learn dependency

---

pyglmnet.py
resources.md

- remove alpha from loss function since we already define when creating GLM class
- enhance `resource.md`

Remove alpha from loss function

---

setup.py

just copy pasted the setup file from another repo with some minor modifications
If you want to work on it while it is installed, just do:
```python setup.py develop install```

Add installer so it can be accessed from any folder

---

README.md
pyglmnet/pyglmnet.py

- printing INFO log to console

Output log to console

---

README.md

a small change. The links don't render very well in my browser. I think nbviewer works pretty well across browsers.

use nbviewer instead of github viewer

---

README.md
pyglmnet/pyglmnet.py
setup.py

Now, we accept input of flatten array or column array

Allow output array to be more flexible

---

README.md

replaced score with StandardScaler

---

.travis.yml
pyglmnet/__init__.py
setup.cfg

This will make tests get run every time a pull request is made.
@pavanramkumar you will have to activate your Travis for pyglmnet and then we can merge this PR.

Set up continuous integration

---

README.md
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

Previous code was wrongly collapsing gradient of intercept parameters. Also, logLL was retuning negative log-likelihood.

Multinomial intercept gradient and LL fix (Close #10)

---

pyglmnet/pyglmnet.py

- I added some checking in `__init__` for `reg_lambda`
- Also change `threshold` to `tol` which default is set to `1e-3`, for the convergence criteria (this one I follow `sklearn` format)

Allow reg_lambda to be number, change threshold to tol (follow sklearn)

---

.travis.yml
pyglmnet/pyglmnet.py
setup.cfg

This will make sure we adhere to flake8 :)

integrate flake8 with travis

---

pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

closes #37 
I'm not sure if I did all the possible checks, but we should slowly aim to test as much as possible. That will speed up development and avoid bugs.

Allow slicing glm object + add repr

---

pyglmnet/pyglmnet.py

closes https://github.com/pavanramkumar/pyglmnet/issues/56
@hugoguh is it working now?

FIX verbose

---

README.md

adding coverage info as well to readme :)

add_coveralls

---

.travis.yml
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

closes https://github.com/pavanramkumar/pyglmnet/issues/70
@pavanramkumar the `'poissonexp'` link function appears to be broken (?). Take a look at the `beta` in the test. They are way off from the simulated ones ...

improve tests

---

pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

docstring conventions and random_state

---

pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

Pseudo-R2, deviance, and simulate for multinomial. Close #80

---

circle.yml

closes https://github.com/pavanramkumar/pyglmnet/issues/82
... need to first test on my fork if this works or not.
Once this works, it will check if the docs build fine whenever a PR is made. So, the likelihood of an error in the docs will be minimal ...

MRG: add circle yml file

---

setup.py

[MRG] Fix setup

---

examples/plot_poisson.py
examples/plot_poisson_2.py
tests/test_pyglmnet.py

I refactored some variable names on the example and test files so that same objects have same variable names. (issue #92).

Refactored variable names (issue #92)

---

README.md

- renamed the variables in [Getting Started](https://github.com/pavanramkumar/pyglmnet#getting-started) to match naming convention with rest of project per [this](https://github.com/pavanramkumar/pyglmnet/pull/93/files)
- fixed the resources link that is opening the markdown version of resources

cleaned up the README a little

---

doc/Makefile
pyglmnet/pyglmnet.py

- I've made some changes in the _doc/Makefile_ document in order for it to make a proper cleaning of generated files.
- The _softmax_ function was lacking of documentation.
Should _softmax_ function documentation be exposed at the online documentation web site?

Doc Makefile clean command refactored and softmax function detailed documentation

---

doc/Makefile
doc/conf.py
doc/index.rst
examples/README.txt
examples/api/README.txt
examples/api/plot_poisson.py
examples/api/plot_poisson_2.py
examples/application/README.txt
examples/benchmarks/README.txt
tutorial/README.txt
tutorial/plot_tutorial.py

Per [#106](https://github.com/pavanramkumar/pyglmnet/issues/106)

WIP: reorganizing documentation 

---

doc/index.rst
doc/install.rst
doc/start.rst
examples/api/plot_poisson.py
examples/api/plot_poisson_2.py

@the872 
I think something weird happened when you added your commits to my branch. Did you make sure to clone the repo first? It erased my commits! 
In any case, I've done the easiest fix which is to make a PR through a new branch.

Cleaning docs index install and start

---

Makefile
doc/Makefile

[MRG] Updating the Makefiles

---

pyglmnet/pyglmnet.py

as per [#116](https://github.com/pavanramkumar/pyglmnet/issues/116)

[MRG] [ref#116] cleaned up comments

---

README.md

[mrg] updated travis badge to .svg

---

doc/developers.rst

as per [#113](https://github.com/pavanramkumar/pyglmnet/issues/113)

[mrg] [ref#113] added doc dependencies 

---

pyglmnet/pyglmnet.py

Default value of alpha should be 0.5 instead of 0.05

Fixed alpha initialization bug

---

pyglmnet/pyglmnet.py

closes https://github.com/pavanramkumar/pyglmnet/issues/141
cc @evadyer

FIX norm -> norm ** 2

---

pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

- implement group lasso prox operator in `_prox` function
- added test
this address issue #137

group lasso

---

pyglmnet/pyglmnet.py
pyglmnet/utils.py
tests/test_pyglmnet.py

- implemented Tikhonov both for solvers (`batch-gradient` and `cdfast`)
- tested that it runs better than ridge regression on simulated data
- unit test
todo:
- API example
- application example

[MRG] tikhonov regularization

---

pyglmnet/pyglmnet.py

fixed random state issue

---

examples/api/plot_multinomial.py
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

[MRG] added predict_proba for multinomial

---

examples/plot_community_crime.py
pyglmnet/datasets.py

- wrote a dataset fetcher to grab `communities.data`
- removed missing values
- removed comparison with `scikit-learn` (we should use `BenchmarkGLM()` for all comparisons)
this addresses #149

updated crime example with dataset fetcher

---

examples/plot_group_lasso.py
pyglmnet/datasets.py
pyglmnet/pyglmnet.py

added in requested fixes from the last PR, may still need to fix some flake8 errors

[MRG] Group lasso branch

---

circle.yml
doc/api.rst
doc/conf.py
doc/developers.rst
doc/index.rst
doc/install.rst
doc/requests.rst
doc/start.rst
doc/tutorial.rst
pyglmnet/pyglmnet.py

still to do:
- ~add a list of requests to the requests.rst page~
- ~expand the tutorial to include group Lasso and Tikhonov~
this addresses #1 and #106
have a look at circle CI artifacts if you'd like to see how the docs look now.

[WIP] reorganization of docs

---

.gitignore
README.md
distribution_instructions.md
setup.cfg
setup.py

This should include the info needed for pip distribution.

[MRG] Pip setup branch

---

doc/cheatsheet.rst
pyglmnet/__init__.py
pyglmnet/pyglmnet.py

[MRG] fixed bug in linearized poisson gradient and hessian

---

pyglmnet/__init__.py
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

Here's a quick sketch of something I'd like to do. Basically it's a way for us to test the gradients ...
@pavanramkumar let me know if you are okay with changes along this line. Otherwise, it's something we can discuss during the sprint.

WIP check gradients

---

README.md
doc/developers.rst

looks like I forgot to update this file in my last PR ...

remove list of authors

---

.travis.yml
pyglmnet/pyglmnet.py

Python3 Travis CI

---

README.md
doc/cheatsheet.rst
doc/whats_new.rst
pyglmnet/pyglmnet.py
pyglmnet/utils.py
tests/test_pyglmnet.py

closes https://github.com/glm-tools/pyglmnet/issues/189

[MRG] gamma link function

---

pyglmnet/pyglmnet.py

closes https://github.com/glm-tools/pyglmnet/issues/212

[MRG] Not too many n_samples and np.transpose -> .T

---

doc/index.rst
pyglmnet/__init__.py
pyglmnet/metrics.py
pyglmnet/pyglmnet.py
pyglmnet/utils.py

This is built on top of https://github.com/glm-tools/pyglmnet/pull/216.
@pavanramkumar there are some differences between the two functions that I don't understand. Perhaps you could explain to me over chat

[MRG] Refactor log likelihood.

---

pyglmnet/__init__.py
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

This PR is on top of https://github.com/glm-tools/pyglmnet/pull/217
Diff will look cleaner once that PR is merged. I'll also try to add tests for hessian and the hessian for gamma GLM here

Refactor hess

---

tests/test_pyglmnet.py

Test for Solver Invariance

---

pyglmnet/datasets.py
tests/test_pyglmnet.py

FIX py3 for urllib

---

pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

ENH add check for distr

---

pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

[MRG] callbacks and modified convergence criteria

---

doc/whats_new.rst

closes #260 
It's WIP. Since it's a little repetitive task, I'll finish it when I'm at the library later today.
We should make sure to update it before merging a pull request from now on.

[MRG] Update what's new

---

doc/whats_new.rst
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

Changes summary
-  Update `simulate_glm` to use a `RandomState` instance initialized with `random_state`;
-  Update `GLM` to use a `RandomState` instance initialized with `random_state`;
-  Add a test to ensure correctness of the results when setting `random_state` (this may require a more close review);
- Update `what's_new.rst` with the bugfix news.

[MRG+1] Fix issue #269.

---

doc/cheatsheet.rst
doc/conf.py
doc/developers.rst
doc/index.rst
doc/tutorial.rst

Quickly read through docs and made some minor changes.

Minor changes to docs: spelling, links, etc

---

.travis.yml
README.rst
pyglmnet/__init__.py
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

- Using `ALLOWED_DISTRS` instead of re-defining allowed distributions in the context of testing.
- Added more sanitation of user inputs to `fit` and `score`.
- Wrote some tests to solidify the API.

Tests for API, more input checks

---

pyglmnet/datasets.py

scipy.special.comb replaces recently-removed scipy.misc.comb

---

doc/whats_new.rst
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

@peterfoley @cxrodgers @opieters
can you see if this solves your use-case?
closes https://github.com/glm-tools/pyglmnet/pull/277 https://github.com/glm-tools/pyglmnet/pull/287 https://github.com/glm-tools/pyglmnet/pull/314

record number of iterations

---

doc/whats_new.rst
pyglmnet/pyglmnet.py
pyglmnet/utils.py
tests/test_pyglmnet.py

Add fit_intercept parameter to GLM and GLMCV #308

[MRG] Add fit_intercept parameter to GLM and GLMCV (see issue #308)

---

README.rst
doc/whats_new.rst
pyglmnet/pyglmnet.py
tests/test_metrics.py
tests/test_pyglmnet.py

MRG: allow beta to be only 1D instead of both 1D and 2D

---

README.rst
doc/install.rst

DOC simplify installation of bleeding edge

---

README.rst
doc/index.rst

[MRG] DOC add documentation for both stable and development version

---

.travis.yml
MANIFEST.in
Makefile
examples/plot_community_crime.py
examples/plot_tikhonov.py
requirements.txt

MRG: add manifest.in

---

.circleci/config.yml
tests/test_pyglmnet.py

@pavanramkumar looks like I don't have write permissions so I can just rebuild CircleCI. Anyway, I think it's better to increase the timeout a bit. Let's see if this is more stable

MAINT increase timeout and FIX test_random_state_consistency

---

.travis.yml
README.rst

Added check for readme to travis using twine. It closes #337

Add check for readme to travis

---

doc/tutorial.rst
doc/whats_new.rst
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

[MRG] control Hessian term explosion

---

.mailmap

@jasmainak is this the proper formatting?

Adding Mayank E-mail

---

paper/paper.bib

Fix issue with JOSS submission as stated here https://github.com/openjournals/joss-reviews/issues/1921.

Add missing DOIs to paper.

---

.circleci/config.yml
examples/plot_tikhonov.py
paper/paper.bib
paper/paper.md

example usage

---

.travis.yml
README.rst

@pavanramkumar @titipata @geektoni here is my attempt at improving the readme example. Let me know what you think

DOC: improve readme example

---

doc/install.rst
doc/start.rst

- Adding requirements for building documentation
- Adding bits of information about scikit-learn's compatibility

Update documentation according to JOSS paper

---

doc/tutorial.rst

This PR is a follow-up of #370  and #371 ,

align multiple-line equations properly

---

README.rst
doc/citation.rst
doc/index.rst

This is related to issue #360.

Add how to cite pyglmnet

---

setup.py

This was my mistake when adding `externals` folder. We have to fix the `setup.py` too.

Fix problem externals does not get included

---

doc/conf.py
doc/contributing.rst
examples/plot_glm_retinal_ganglia.py
pyglmnet/__init__.py
pyglmnet/datasets.py
pyglmnet/pyglmnet.py

This pull request contains a tutorial for linear Gaussian and Poisson GLM. This PR need the dataset from https://github.com/glm-tools/datasets/pull/1.

[MRG] Add Pillow's tutorial for RGC spikes prediction

---

.circleci/config.yml
doc/api.rst
doc/whats_new.rst
examples/plot_glm_retinal_ganglia.py
examples/plot_group_lasso.py
examples/plot_tikhonov.py
pyglmnet/__init__.py
pyglmnet/datasets.py

- Adding download dataset to CircleCI
- Ask for permission if the user has to fetch the data

[MRG] Ask for license agreement when run doc locally

---

doc/contributing.rst
doc/install.rst
doc/whats_new.rst
examples/plot_community_crime.py
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

closes #377 
@pavanramkumar @titipata I think this is a stop gap solution until we make our solvers faster. Okay with you guys?

ENH: add plot for convergence

---

doc/whats_new.rst
pyglmnet/pyglmnet.py
tests/test_pyglmnet.py

This is related to https://github.com/glm-tools/pyglmnet/issues/383 .

Fix the threshold of the proximal operator

---

doc/cheatsheet.rst
doc/whats_new.rst
pyglmnet/metrics.py
pyglmnet/pyglmnet.py
pyglmnet/utils.py
tests/test_pyglmnet.py

closes #163 
* Update the pyglmnet code in order to accept Negative Binomial as distribution family. 
* Update also the test suite.
<del>The `cdfast` is still missing.</del>

[MRG] Add Negative Binomial distribution (see issue #163).
